unique_ids:
  forms:
    Rechner: M4U4FSHVLYPJIYDNJIGPZSECDCMZXE43
  modules: {}
  server_modules: {}
  assets:
    HC_Logo_Icon Kopie.svg: '1712902647863164746823246.21103'
    standard-page.html: R4NEJSPQU66ZIQAUB6GKO3BAWZCPUUE6
    theme.css: TBRZUU6TTM3NYFKPCIGWY63P22FGCS5M
